title: DAM framework
subtitle: Detection & Attribution Modelling Framework
description: A guide to help selecting D&A methods suited to your project
author: Joaquim Estopinan (CNRS), Wilfried Thuiller (CNRS), Risto Heikkinen (SYKE)
theme: just-the-docs
url: https://estopinj.github.io/dam/
baseurl: ""
permalink: pretty

aux_links:
  DAM on GitHub: https://github.com/estopinj/dam
aux_links_new_tab: true

defaults:
  - scope:
      path: "contents" # an empty string here means all files in the project
#      type: "pages"
    values:
      layout: "default"
      assessor: Joaquim Estopinan


# collections_dir: contents
# collections:
#   tests:
#     output: true
# just_the_docs:
#   collections:
#     tests:
#       name: Is it the capital & static collection name?
      

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true


# For copy button on code
enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# # External navigation links
# nav_external_links:
#   - title: Just the Docs on GitHub
#     url: https://github.com/just-the-docs/just-the-docs
#     hide_icon: false # set to true to hide the external link icon - defaults to false
#     opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

liquid:
  error_mode: strict
  strict_filters: true


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all



footer_content: 'Copyright &copy; 2024-2028 Obsgession. Distributed by an <a href="https://github.com/estopinj/dam/tree/main/LICENSE">MIT license.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/estopinj/dam" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
