title: Detection & Attribution  Modelling Franmework 
description: A guide to help selecting D&A methods suited to your project
author: Joaquim Estopinan (CNRS), Wilfried Thuiller (CNRS), Risto Heikkinen (SYKE)
theme: just-the-docs

url: https://estopinj.github.io/dam/

aux_links:
  DAM on GitHub: https://github.com/estopinj/dam
