name: New Method documentation
description: Create a new documentation method page.
title: "[Documentation request]: "
labels: ["method", "documentation"]
assignees:
  - estopinj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation method request!
  - type: input
    id: method_name
    attributes:
      label: Target method name
      description: Name of the existing or intended method page to document.
      placeholder: ex. Frescalo
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Page’s Author & Date
      placeholder: ex. Jean Dupont
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description & principle 
      description: A clear, technical yet accessible explanation of the method, its core principle(s).
      placeholder: This method is used to...
      value: "Method description"
    validations:
      required: true
  - type: textarea
    id: variant
    attributes:
      label: Major variants
      description: If the method has variants that seem important, either already widespread or promising and well documented. 
    validations:
      required: false
  - type: textarea
    id: online_resources
    attributes:
      label: Further online resources
      description: References to useful online resources to get started, e.g. explanation blogs, video tutorials, etc.
      placeholder: ex. https://example.com/method
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Reference articles
  - type: textarea
    id: method_references
    attributes:
      label: Method 
      description: One or a few key academic references that introduce or formalize the method.
      placeholder: ex. DOI or URL
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Research applications
  - type: textarea
    id: rs_data
    attributes:
      label: With RS data in Ecology / Biodiversity
      description: If the method has been used in remote sensing research, please list the references here.
      placeholder: ex. DOI or URL
    validations:
      required: false
  - type: textarea
    id: rs_data_field
    attributes:
      label: Without RS data (Ecology domain)
      description: If the method has been used in research without remote sensing data, please list the references here.
      placeholder: ex. DOI or URL
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Packages
  - type: textarea
    id: python_pkg
    attributes:
      label: Python
      description: Python packages implementing the method.
      placeholder: Link toward the package documentation or repository.
    validations:
      required: false
  - type: textarea
    id: r_pkg
    attributes:
      label: R
      description: R packages implementing the method.
      placeholder: Link toward the package documentation or repository.
    validations:
      required: false
  - type: textarea
    id: code_list
    attributes:
      label: Code Cells
      description: Code implementations or notebooks to run the method.
      placeholder: Code examples to run the method
    validations:
      required: false
