name: Method documentation
description: Submit a new documentation method page or complete an existing one
title: "[Documentation request]: "
labels: ["method", "documentation"]
assignees:
  - estopinj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation method request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: author
    attributes:
      label: Page’s Author & Date
      placeholder: ex. Jean Dupont
    validations:
      required: true


  - type: dropdown
    id: documented_method
    attributes:
      label: Is the method already documented in NaviDAM?
      description: Look if the method is already documented in NaviDAM. If it is, please provide the exact same name below.
      options:
        - Yes
        - No
    validations:
      required: true
  - type: dropdown
    id: assessed_method
    attributes:
      label: Is the method already assessed in NaviDAM?
      description: Look if the method is already assessed in NaviDAM. If it is, please provide the exact same name below.
      options:
        - Yes
        - No
    validations:
      required: true
  - type: input
    id: method_name
    attributes:
      label: Target method name
      description: Name of the existing or intended method page to document.
      placeholder: ex. Frescalo
    validations:
      required: true
  

  
  - type: textarea
    id: description
    attributes:
      label: Description & principle 
      description: A clear, technical yet accessible explanation of the method, its core principle(s).
      placeholder: This method is used to...
      value: "Method description. Images can be added, please provide sources."
    validations:
      required: true
  
  - type: textarea
    id: variant
    attributes:
      label: Major variants
      description: If the method has variants that seem important, either already widespread or promising and well documented. 
    validations:
      required: false
  
  - type: textarea
    id: online_resources
    attributes:
      label: Further online resources
      description: References to useful online resources to get started, e.g. explanation blogs, video tutorials, etc.
      placeholder: ex. https://example.com/method
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ## Reference articles
  
  - type: textarea
    id: method_references
    attributes:
      label: Method 
      description: One or a few key academic references that introduce or formalize the method.
      placeholder: |
        - Examples et al. (2020) Title of the article. Journal Name, 1(1), 1-10. https://doi.org/10.xxxx/xxxx
        - Others et al. (2021)
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ## Research applications
  
  - type: textarea
    id: rs_data
    attributes:
      label: With RS data in Ecology / Biodiversity
      description: If the method has been used in remote sensing research, please list the references here.
      placeholder: |
        - Application A et al. (2022) Title of the article. Journal Name, 1(1), 1-10. https://doi.org/10.xxxx/xxxx
        - Application B et al. (2023)
    validations:
      required: false
  
  - type: textarea
    id: rs_data_field
    attributes:
      label: Without RS data (Ecology domain)
      description: If the method has been used in research without remote sensing data, please list the references here.
      placeholder: |
        - Application C et al. (2023)
        - Application D et al. (2023)
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ## Implementation
  
  - type: textarea
    id: python_pkg
    attributes:
      label: Python
      description: Python implementation of the method.
      placeholder: |
        - Link toward the package documentation or repository
        - Package name on PyPI or conda-forge
    validations:
      required: false
  
  - type: textarea
    id: r_pkg
    attributes:
      label: R
      description: R implementation of the method.
      placeholder: |
        - Link toward the package documentation or repository
        - Package name on CRAN or Bioconductor
    validations:
      required: false
  
  - type: textarea
    id: code_list
    attributes:
      label: Code Cells
      description: Implementation or open-source notebook links to run the method.
      placeholder: Code examples to run the method
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/estopinj/dam/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
