name: Method assessment
description: Submit a new method assessment
title: "[Assessment request]: "
labels: ["method", "assessment"]
assignees:
  - estopinj
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this method assessment!
  - type: input
    id: method_name
    attributes:
      label: Target method name
      description: Name of the existing or intended method page to assess.
      placeholder: ex. Synthetic Control Method
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Page’s Author & Date
      placeholder: ex. Jean Dupont, 14/06/2026
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Assessment logic
        - The assessment should be based on the method's capacity to address a set of objectives, its compatibility with different data types, the assumptions it relies on, etc.
        - Situate the method against the unified criteria of NaviDAM will next enable users to filter down the approaches suited to their needs.
        - There are two types of criteria:
          - *Multiple* - Tick **all** the options that apply to the method.
          - *Ordinal* - Options are ordered and selecting one implies that higher (next) options in the dropdown meanu are also satisfied.

        - One entry can actually correspond to a family of methods (e.g. DiD), with many variants satisfying different criteria.
        In this case, the assessment should be based on the most common or original variant of the method, and add the options matching major & widespread variants.
        For checkbox criteria, assessors should tick all that apply, and for ordinal criteria, they should select the most permissive option.
        - Rationale and comments can be added at the end of the form to justify the assessment or provide any additional information.

        *See the [criteria description](https://estopinj.github.io/dam/criteria) for more details on the criteria and how to assess them*

  - type: markdown
    attributes:
      value: |
        ## Objective

  - type: checkboxes
    id: objective
    attributes:
      label: Objective
      description: Tick all the objectives that the method can address
      options:
        - label: Effect estimation
        - label: Causal relationship(s)
        - label: Predictive task + interpretability
        - label: Detection
        - label: Significance and robustness tests
        - label: Scenario projection
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Outcome
  
  - type: checkboxes
    id: estimand
    attributes:
      label: Estimand
      description: Multiple
      options:
        - label: ATT
        - label: ATE
        - label: LATE
        - label: CATE
        - label: Mediation effects
        - label: Oriented link
        - label: Risk ratios
        - label: Maps & generalisations
        - label: Others
        - label: Inapplicable
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        ## Data compatibility
  
  - type: checkboxes
    id: data_type
    attributes:
      label: Type
      description: Multiple
      options:
        - label: Spatial only (cross-sectional)
        - label: Time-series (one sample)
        - label: Panel data (many samples)
        - label: Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: required_ts_length
    attributes:
      label: Required TS length
      description: Ordinal
      options:
        - Handles ≤ 10
        - ≥ 10
        - ≥ 100
        - Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: handles_few_samples
    attributes:
      label: Handles few samples
      description: Multiple
      options:
        - Yes CT design
        - Yes ≤ 10
        - 10 to 100
        - "No"
        - Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: handles_huge_datasets
    attributes:
      label: Handles huge datasets (n)
      description: Ordinal
      options:
        - "Yes"
        - Most do
        - Most dont
        - "No"
        - Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: handles_missing_data
    attributes:
      label: Handles missing data
      description: Ordinal
      options:
        - "Yes"
        - Partially
        - "No: requires prelim. correction"
        - Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: rs_data_proven
    attributes:
      label: RS-data proven
      description: Ordinal
      options:
        - "Yes"
        - Few applications
        - "No"
        - Inapplicable
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: | 
        ## Model properties
  
  - type: dropdown
    id: requires_explicit_processes
    attributes:
      label: Requires explicit processes
      description: One choice
      options:
        - "Yes"
        - Optional
        - Agnostic
        - Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: exposure_type
    attributes:
      label: Exposure type
      description: Multiple
      options:
        - label: Binary
        - label: Categorical
        - label: Continuous / Time-varying
        - label: Compositional
        - label: Multivariate
        - label: Others
        - label: All
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: number_of_variables
    attributes:
      label: Number of variables
      description: Multiple
      options:
        - label: Univariate
        - label: Bivariate
        - label: Multivariate
        - label: High-dimensional (p≫n)
        - label: Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: propagates_uncertainty
    attributes:
      label: Propagates uncertainty
      description: Ordinal
      options:
        - Inherent capacity
        - Model-specific tools
        - Needs model-agnostic propagation
        - Inapplicable
    validations:
      required: true
  
  - type: dropdown # Ordinal criteria
    id: handles_lag_effects
    attributes:
      label: Handles lag effects
      options:
        - "Yes"
        - Possible
        - "No"
        - Inapplicable
    validations:
      required: true

  - type: checkboxes
    id: parametric_nature
    attributes:
      label: Parametric nature
      description: Multiple
      options:
        - label: Parametric
        - label: Semi-parametric
        - label: Non-parametric
        - label: Rule-based
        - label: Inapplicable
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: | 
        ## Packages
  
  - type: checkboxes
    id: language
    attributes:
      label: Language
      options:
        - label: R
        - label: Python
        - label: GIS
        - label: Others
        - label: No package
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: usage
    attributes:
      label: Usage
      options:
        - label: User-friendly
        - label: Technical but well documented
        - label: Sparse documentation
        - label: Domain-specific skills
        - label: Varying
        - label: Inapplicable
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ## Assumptions
  
  - type: checkboxes
    id: functional_form
    attributes:
      label: Functional form
      description: Multiple
      options:
        - label: Linear
        - label: Quadratic
        - label: Non-linear
        - label: Additivity
        - label: Assumption-free
        - label: Rule-based
        - label: Log-linear
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: no_unobserved_confounders
    attributes:
      label: No unobserved confounders
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Time-varying OR site-varying
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: no_interference
    attributes:
      label: No interference
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Not required
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: well_defined_treatments
    attributes:
      label: Well-defined treatments
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: common_support_positivity
    attributes:
      label: Common support (positivity)
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: causal_markov_condition
    attributes:
      label: Causal Markov Condition
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: faithfulness
    attributes:
      label: Faithfulness
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: idd
    attributes:
      label: IDD
      description: Multiple
      options:
        - label: Required
        - label: Recommended
        - label: Desirable
        - label: Relaxes assumption
        - label: Inapplicable
    validations:
      required: true
  
  - type: checkboxes
    id: model_specific_assumptions
    attributes:
      label: Model-specific assumptions
      description: Multiple
      options:
        - label: Parallel trends
        - label: Stationarity
        - label: Dispersal / reproduction / mortality
        - label: Instrument validity
        - label: Normality of random effects
        - label: No M-O confounding
        - label: Good covariate balance
        - label: Effect entirely mediated
        - label: Cutoff + PO continuity
        - label: B/A treatment obs.
        - label: Good pretreatment fit
        - label: No specific
    validations:
      required: true


  - type: textarea
    id: rationale
    attributes:
      label: Rationale and additional comments
      placeholder: Any rationale you would like to share about the method assessment, how/why some options were chosen, or any other comment you would like to share.
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://estopinj.github.io/dam/contributing/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
