"""Bulk assess 58 incomplete methods. Uses only predefined options from TSV distinct values + criteria.js."""
import csv
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
IN = PROJECT_ROOT / "_data" / "DetectionAttribution methods - Method Assessment.tsv"
RES = PROJECT_ROOT / "_data" / "DA_usedressources.tsv"

HDR = ['Author','Status','Reviewer','Assessor','Method','Status','AI-assisted','AI flag','Category','Sub-category','Objective','Estimand','Type','Minimal TS length','Handles few samples','Handles huge datasets (n)','Handles missing data','RS-data proven','Fonctional form','No unobserved confounders','No interference','Well-defined treatments','Common support (positivity)','Causal Markov Condition','Faithfulness','IID','Model specific','Requires explicit processes','Exposure type','Number of variables','Propaguates uncertainty','Handles lag effects','Parametric nature','Language','Usage']

# Each entry: method -> dict of columns to set (Status->To review, AI-assisted->Yes, Assessor appends AI tag always)
AI_TAG = "AI initial completion"
A = {}
def put(method, **kw):
    base = {"Status": "To review", "AI-assisted": "Yes"}
    base.update(kw)
    A[method] = base

# 1 Matrix completion (Athey et al 2021 panel, low-rank)
put("Matrix completion", **{"AI flag": "Ambiguous: interactive fixed effects relax some unobserved confounding but still require low-rank + no interference; RS applications scarce.",
"Category": "Quasi-experiments, Adjusted methods (Backdoor C.)", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good pretreatment fit, Time-varying OR site-varying",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Categorical",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Semi-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 2 F-learner
put("Target transformation (F-learner)", **{"AI flag": "Ambiguous: transformed-target variance high; needs large n; binary/categorical treatment primarily.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "CATE, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 3 S,T,X learners
put("S,T, X learners", **{"AI flag": "Ambiguous: S/T/X variants differ in sample efficiency and overlap sensitivity; grouped as one row.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "CATE, ATE, ATT", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 4 NNs (Dragonnet-type)
put("NNs", **{"AI flag": "Ambiguous: covers Dragonnet-type causal-effect NNs; attribution/interpretability NN variants differ; needs large n.",
"Category": "Causal ML", "Objective": "Effect estimation",
"Estimand": "ATE, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Technical but well documented, Domain-specific skills"})
# 5 BART
put("BART", **{"AI flag": "",
"Category": "Causal ML, Alternative paradigms", "Objective": "Effect estimation",
"Estimand": "ATE, ATT, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Inherent capacity", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 6 R-learner TMLE MTP
put("R-learner, TMLE, MTP", **{"AI flag": "Ambiguous: grouped row covers R-learner, TMLE and MTP which differ in estimands and robustness; assess as doubly-robust meta-learner family.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "ATE, ATT, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 7 RL
put("Reinforcement learning", **{"AI flag": "Ambiguous: broad family (policy learning, dynamic treatment regimes); assessment for sequential decision setting.",
"Category": "Causal ML", "Objective": "Effect estimation, Scenario projection",
"Estimand": "CATE, Others", "Type": "Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Relaxes assumption", "Model specific": "Proposed: sequential ignorability / Markov decision assumption",
"Requires explicit processes": "Agnostic", "Exposure type": "Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 8 PC PCMCI
put("PC, PCMCI", **{"AI flag": "",
"Category": "Causal discovery", "Sub-category": "Constraint-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Required", "Faithfulness": "Required",
"IID": "Recommended", "Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 9 FCI TsFCI
put("FCI, TsFCI", **{"AI flag": "Ambiguous: FCI relaxes causal sufficiency but needs large samples; time-series variant needs stationarity.",
"Category": "Causal discovery", "Sub-category": "Constraint-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Binary, Categorical",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 10 GES TsGFCI
put("GES, TsGFCI", **{"AI flag": "Ambiguous: grouped score-based GES and time-series GFCI; GFCI relaxes sufficiency.",
"Category": "Causal discovery", "Sub-category": "Score-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 11 DYNOTEARS
put("DYNOTEARS", **{"AI flag": "",
"Category": "Causal discovery, Causal ML", "Sub-category": "Continuous optimization",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Yes",
"Parametric nature": "Parametric, Non-parametric", "Language": "Python",
"Usage": "Technical but well documented"})
# 12 LiNGAM
put("LiNGAM", **{"AI flag": "",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: non-Gaussianity of disturbances", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Possible",
"Parametric nature": "Parametric, Semi-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 13 ANM
put("Additive noise models", **{"AI flag": "",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Additivity",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: additive independent noise", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 14 BN learning
put("Bayesian network learning", **{"AI flag": "Ambiguous: broad family (constraint, score, hybrid); assessment for generic DAG learning.",
"Category": "Causal discovery, Alternative paradigms", "Objective": "Causal relationship(s)",
"Estimand": "Oriented link", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Parametric, Non-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 15 IGCI
put("Info-geom. causal inference", **{"AI flag": "Ambiguous: bivariate method; multivariate use via pairwise comparisons.",
"Category": "Alternative paradigms", "Objective": "Causal relationship(s)",
"Estimand": "Oriented link", "Type": "Spatial only (cross-sectional)",
"Minimal TS length": "Inapplicable", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Required",
"Model specific": "Proposed: independence of cause distribution and mechanism",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Bivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 16 SES network
put("SES & Network analysis (~adjusted method)", **{"AI flag": "Ambiguous: umbrella label for SES/network descriptive + adjusted analyses; causal interpretation needs extra assumptions.",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)",
"Objective": "Causal relationship(s), Effect estimation",
"Estimand": "Oriented link, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Relaxes assumption",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Optional",
"Exposure type": "Binary, Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Possible",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 17 diffusion
put("Causal diffusion models", **{"AI flag": "Ambiguous: emerging generative counterfactual approach; RS evidence limited.",
"Category": "Alternative paradigms", "Objective": "Effect estimation, Scenario projection",
"Estimand": "ATE, CATE, Maps & generalisations",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Possible",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 18 MSM
put("Marginal structural models", **{"AI flag": "",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)", "Sub-category": "Intermediate confounding",
"Objective": "Effect estimation", "Estimand": "ATE, ATT",
"Type": "Panel data (many samples)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Linear, Non-linear", "No unobserved confounders": "Required",
"No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended",
"Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 19 G methods
put("G methods", **{"AI flag": "Ambiguous: grouped g-formula, g-estimation and MSM family for time-varying confounding.",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)", "Sub-category": "Intermediate confounding",
"Objective": "Effect estimation", "Estimand": "ATE, ATT, CATE",
"Type": "Panel data (many samples), Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Required",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 20 ICP
put("Invariant causal prediction", **{"AI flag": "",
"Category": "Alternative paradigms, Causal discovery", "Sub-category": "Prediction-based approaches",
"Objective": "Causal relationship(s), Effect estimation", "Estimand": "Oriented link, CATE",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Proposed: invariance across environments", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 21-24 visualisation helpers
for m in ["Treatment assignment graph", "Covariate timeline", "Reporting measures", "Best practice boxes"]:
    put(m, **{"AI flag": "Ambiguous: visualisation/documentation helper, not an estimator; causal criteria marked Inapplicable where appropriate.",
    "Category": "Versatile tools", "Sub-category": "Visualisation helpers",
    "Objective": "Significance and robustness tests", "Estimand": "Others",
    "Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
    "Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
    "Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
    "RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
    "No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
    "Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
    "Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
    "Model specific": "", "Requires explicit processes": "Agnostic",
    "Exposure type": "Binary, Categorical, Continuous / Time-varying",
    "Number of variables": "Multivariate", "Propaguates uncertainty": "Inapplicable",
    "Handles lag effects": "No", "Parametric nature": "Inapplicable",
    "Language": "R, Python", "Usage": "User-friendly"})
# 25 partial identification
put("Partial identification", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools, Robustness & significance tests",
"Objective": "Significance and robustness tests, Effect estimation", "Estimand": "ATE, ATT, Others",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Relaxes assumption", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Relaxes assumption",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 26 sensitivity
put("Sensitivity analyses", **{"AI flag": "",
"Category": "Versatile tools, Ecology-guided Modelling", "Sub-category": "Robustness & significance tests, Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 27 placebo
put("Placebo tests", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Robustness & significance tests",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "Good pretreatment fit", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Inapplicable", "Language": "R, Python", "Usage": "Technical but well documented"})
# 28 power
put("Power analyses", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Robustness & significance tests",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 29 counterfactual explanations
put("Counterfactual explanations", **{"AI flag": "Ambiguous: interpretability tool for ML predictions; causal validity needs extra assumptions.",
"Category": "Versatile tools", "Sub-category": "Causal interpretability",
"Objective": "Predictive task + interpretability", "Estimand": "Others",
"Type": "Spatial only (cross-sectional)", "Minimal TS length": "Inapplicable",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Yes",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Recommended",
"No interference": "Recommended", "Well-defined treatments": "Recommended",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 30 do-calculus
put("Do-calculus rules", **{"AI flag": "",
"Category": "Adjusted methods (Backdoor C.)", "Sub-category": "Alternative effect identification methods",
"Objective": "Effect estimation, Causal relationship(s)", "Estimand": "ATE, Mediation effects, Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "All", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Domain-specific skills"})
# 31 linear quadratic trend
put("Linear, quadratic", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Yes", "Fonctional form": "Linear, Quadratic",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "User-friendly"})
# 32 BFast
put("BFast", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Trend, Abrupt change",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Linear, Additivity",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Semi-parametric", "Language": "R, Python",
"Usage": "Technical but well documented, User-friendly"})
# 33 DL change
put("DL change detection", **{"AI flag": "Ambiguous: broad family of supervised/unsupervised deep change detectors; RS performance varies by architecture.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Abrupt change, Maps & generalisations",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Technical but well documented"})
# 34 diversity metrics
put("Diversity metrics, turnover, variance, phenology, sentinels", **{"AI flag": "Ambiguous: grouped biodiversity indicators, not a single estimator.",
"Category": "Independent detection", "Sub-category": "Frequently monitored indices",
"Objective": "Detection", "Estimand": "Trend, Abrupt change, Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Compositional",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 35 Bayesian structured TS
put("Bayesian Structured TS", **{"AI flag": "Ambiguous: covers BSTS/CausalImpact-style structural time-series; needs pre-period fit.",
"Category": "Alternative paradigms", "Objective": "Effect estimation, Detection, Scenario projection",
"Estimand": "ATT, Trend, Abrupt change", "Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Additivity, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good pretreatment fit, B/A treatment obs., Stationarity",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Continuous / Time-varying",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Inherent capacity",
"Handles lag effects": "Yes", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 36 TRIM
put("TRIM", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Log-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Others", "Usage": "User-friendly"})
# 37 Markov switching AR
put("Markov switching autoregression models", **{"AI flag": "",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Trend, Abrupt change", "Type": "Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Bivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 38 bootstrapping
put("Bootstrapping", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Univariate, Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 39 Causal GNNs
put("Causal GNNs", **{"AI flag": "Ambiguous: emerging family; graph construction choices strongly affect validity.",
"Category": "Causal ML", "Objective": "Effect estimation, Causal relationship(s)",
"Estimand": "CATE, ATE, Oriented link", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Relaxes assumption",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Relaxes assumption",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Possible",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 40 conformal
put("Conformal inference", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "Python, R", "Usage": "Technical but well documented"})
# 41 first-difference
put("First-difference estimator", **{"AI flag": "",
"Category": "Quasi-experiments", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Parallel trends, B/A treatment obs.", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 42 long difference
put("Long difference estimator", **{"AI flag": "",
"Category": "Quasi-experiments", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Parallel trends, B/A treatment obs.", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 43 variance partitioning
put("Variance partitioning / Variable importance", **{"AI flag": "Ambiguous: descriptive attribution of variance, not intervention causality without extra assumptions.",
"Category": "Ecology-guided Modelling", "Objective": "Predictive task + interpretability, Detection",
"Estimand": "Others, Maps & generalisations", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric, Semi-parametric", "Language": "R, Python",
"Usage": "User-friendly, Technical but well documented"})
# 44 moderator
put("Moderator analysis", **{"AI flag": "",
"Category": "Adjusted methods (Backdoor C.)", "Objective": "Effect estimation",
"Estimand": "CATE, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Parametric, Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 45 process-based models
put("Process-based models", **{"AI flag": "",
"Category": "Counterfactual & future simulations", "Objective": "Scenario projection, Effect estimation",
"Estimand": "Maps & generalisations, Trend, Others",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "Dispersal, reproduction, mortality", "Requires explicit processes": "Yes",
"Exposure type": "Continuous / Time-varying, Categorical, Multivariate",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Parametric, Semi-parametric",
"Language": "R, Python, Others", "Usage": "Domain-specific skills"})
# 46 CLUE
put("CLUE model", **{"AI flag": "Ambiguous: land-use allocation scenario model; causal interpretation needs scenario assumptions.",
"Category": "Counterfactual & future simulations", "Objective": "Scenario projection",
"Estimand": "Maps & generalisations", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Rule-based",
"No unobserved confounders": "Recommended", "No interference": "Relaxes assumption",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Yes",
"Exposure type": "Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Parametric, Rule-based",
"Language": "Others, GIS", "Usage": "Domain-specific skills, Technical but well documented"})
# 47 ARDL
put("ARDL", **{"AI flag": "",
"Category": "Ecology-guided Modelling, Adjusted methods (Backdoor C.)", "Sub-category": "Linear regressions & extensions",
"Objective": "Effect estimation, Detection", "Estimand": "ATE, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Parametric", "Language": "R, Python, Others",
"Usage": "Technical but well documented"})
# 48 Bayesian change point
put("Bayesian Change point detection", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Abrupt change, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Bivariate",
"Propaguates uncertainty": "Inherent capacity", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 49 Functional causal model
put("Functional causal model", **{"AI flag": "Ambiguous: umbrella for ANM/LiNGAM-type functional models; specific asymmetry assumption varies.",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Non-linear, Additivity",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: restricted functional form with independent noise",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Semi-parametric, Non-parametric",
"Language": "Python, R", "Usage": "Technical but well documented"})
# 50 CCDC
put("Continuous Change Detection and Classification (CCDC)", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Trend, Abrupt change",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Yes",
"RS-data proven": "Yes", "Fonctional form": "Linear, Additivity",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Semi-parametric", "Language": "Python, Others, GIS",
"Usage": "Technical but well documented, User-friendly"})
# 51 Mann-Kendall
put("Mann-Kendall test (+ seq. extension)", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection, Significance and robustness tests", "Estimand": "Trend",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "Partially", "RS-data proven": "Yes",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 52 Pettitt
put("Pettitt's Test", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection, Significance and robustness tests", "Estimand": "Abrupt change",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 53 Sen slope
put("Sen's slope", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "Partially", "RS-data proven": "Yes",
"Fonctional form": "Linear", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 54 BA detection
put("BA detection", **{"AI flag": "Ambiguous: groups operational burned-area RS products/algorithms; sensor and threshold choices vary.",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Abrupt change, Maps & generalisations",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, Handles ≤ 10", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Yes",
"RS-data proven": "Yes", "Fonctional form": "Rule-based, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Rule-based",
"Language": "Python, Others, GIS", "Usage": "User-friendly, Technical but well documented"})
# 55 Information transfer
put("Information transfer", **{"AI flag": "Ambiguous: umbrella for transfer entropy / information-flow measures; bivariate predictive causality, not intervention causality.",
"Category": "Causal discovery, Alternative paradigms", "Sub-category": "Prediction-based approaches",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 56 CAT transformation
put("CAT transformation (Hird et al. 2016)", **{"AI flag": "Ambiguous: single-study change-after-transformation detector; general validity beyond original context uncertain.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Abrupt change, Trend", "Type": "Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 57 Trajectory classification
put("Trajectory classification (Pélissié et al. 2024)", **{"AI flag": "Ambiguous: single-study trajectory classifier; general validity beyond original context uncertain.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Trend, Maps & generalisations", "Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Non-parametric, Rule-based",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 58 Dynamical footprint
put("Dynamical footprint analysis (Cano et al. 2025)", **{"AI flag": "Ambiguous: single-study dynamical-footprint detector; general validity beyond original context uncertain.",
"Category": "Independent detection", "Objective": "Detection, Causal relationship(s)",
"Estimand": "Oriented link, Abrupt change, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "Dynamical system", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})

def main():
    with open(IN, encoding="utf-8", newline="") as f:
        content = f.read()
    lines = content.split("\n")
    # header line index 3 (has duplicate 'Status': idx1=doc Status, idx5=assessment Status)
    hdr = [h.strip() for h in lines[3].split("\t")]
    assert hdr == HDR, f"header mismatch: {hdr[:6]}"
    updated = 0
    for i in range(4, len(lines)):
        if not lines[i].strip():
            continue
        parts = lines[i].split("\t")
        while len(parts) < len(HDR):
            parts.append("")
        method = parts[4].strip()
        status = parts[5].strip()
        if status == "Incomplete" and method in A:
            patch = A[method]
            for k, v in patch.items():
                # 'Status' key means assessment Status at index 5 (not doc Status at index 1)
                if k == "Status":
                    j = 5
                else:
                    j = HDR.index(k)
                parts[j] = v
            # Always overwrite Assessor with the AI tag (assessment was empty)
            parts[3] = AI_TAG
            # ensure length
            lines[i] = "\t".join(parts[:len(HDR)])
            updated += 1
    with open(IN, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))
    print(f"updated {updated} rows")

if __name__ == "__main__":
    main()
