"""Bulk assess 58 incomplete methods. Uses only predefined options from TSV distinct values + criteria.js."""
import csv
import json
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
IN = PROJECT_ROOT / "_data" / "DetectionAttribution methods - Method Assessment.tsv"
RES = PROJECT_ROOT / "_data" / "DA_usedressources.tsv"
MANUAL_RES = PROJECT_ROOT / "_data" / "manual_resources.json"

HDR = ['Author','Doc status','Reviewer','Assessor','Method','Assessment status','AI-assisted','AI flag','Category','Sub-category','Objective','Estimand','Type','Minimal TS length','Handles few samples','Handles huge datasets (n)','Handles missing data','RS-data proven','Fonctional form','No unobserved confounders','No interference','Well-defined treatments','Common support (positivity)','Causal Markov Condition','Faithfulness','IID','Model specific','Requires explicit processes','Exposure type','Number of variables','Propaguates uncertainty','Handles lag effects','Parametric nature','Language','Usage','Confidence in assessment']

# Each entry: method -> dict of columns to set (Status->To review, AI-assisted->Yes).
AI_TAG = "AI initial completion"
CORRECTED_AI_TAG = "AI corrected completion"
with open(MANUAL_RES, encoding="utf-8") as _manual_file:
    CORRECTED_METHODS = set(json.load(_manual_file).keys())

A = {}
def put(method, **kw):
    base = {"Status": "To review", "AI-assisted": "Yes"}
    base.update(kw)
    A[method] = base

# 1 Matrix completion (Athey et al 2021 panel, low-rank)
put("Matrix completion", **{"AI flag": "Ambiguous: interactive fixed effects relax some unobserved confounding but still require low-rank + no interference; RS applications scarce.",
"Category": "Quasi-experiments, Adjusted methods (Backdoor C.)", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good pretreatment fit, Time-varying OR site-varying",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Categorical",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Semi-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 2 F-learner
put("Target transformation (F-learner)", **{"AI flag": "Ambiguous: transformed-target variance high; needs large n; binary/categorical treatment primarily.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "CATE, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 3 S,T,X learners
put("S,T, X learners", **{"AI flag": "Ambiguous: S/T/X variants differ in sample efficiency and overlap sensitivity; grouped as one row.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "CATE, ATE, ATT", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 4 NNs (Dragonnet-type)
put("NNs", **{"AI flag": "Ambiguous: covers Dragonnet-type causal-effect NNs; attribution/interpretability NN variants differ; needs large n.",
"Category": "Causal ML", "Objective": "Effect estimation",
"Estimand": "ATE, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Technical but well documented, Domain-specific skills"})
# 5 BART
put("BART", **{"AI flag": "",
"Category": "Causal ML, Alternative paradigms", "Objective": "Effect estimation",
"Estimand": "ATE, ATT, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Inherent capacity", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 6 R-learner
put("R-learner", **{"AI flag": "Method primarily targets CATE (heterogeneous treatment effects); ATE requires post-estimation aggregation of individual treatment effects rather than direct estimation by the learner itself.",
"Category": "Causal ML", "Sub-category": "Meta-learners", "Objective": "Effect estimation",
"Estimand": "CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 7 TMLE
put("Targeted Maximum Likelihood Estimation (TMLE)", **{"AI flag": "TMLE combines nuisance-model fitting with a targeting step to achieve semiparametric efficiency; row reflects generic point-treatment observational estimation, while longitudinal variants extend the same logic.",
"Category": "Adjusted methods (Backdoor C.), Causal ML", "Objective": "Effect estimation",
"Estimand": "ATE, ATT, CATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Inherent capacity", "Handles lag effects": "Possible",
"Parametric nature": "Semi-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 8 Modified treatment policies
put("Modified Treatment Policies", **{"AI flag": "MTP framework is for realistic policy-dependent interventions rather than static ATE comparisons; linked resources emphasize sequential/longitudinal settings with time-dependent confounding under sequential exchangeability.",
"Category": "Alternative paradigms, Causal ML", "Sub-category": "Intermediate confounding", "Objective": "Effect estimation, Scenario projection",
"Estimand": "CATE, Others", "Type": "Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Recommended", "Model specific": "Proposed: sequential exchangeability under policy intervention", "Requires explicit processes": "Agnostic",
"Exposure type": "Categorical, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R", "Usage": "Technical but well documented"})
# 9 RL
put("Reinforcement learning", **{"AI flag": "Broad family (Q-learning, policy-gradient, actor-critic); assessment assumes sequential decision settings with Markov-style dynamics and dynamic treatment-regime optimization rather than static effect estimation.",
"Category": "Causal ML", "Objective": "Effect estimation, Scenario projection",
"Estimand": "CATE, Others", "Type": "Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Required",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Recommended", "Faithfulness": "Recommended",
"IID": "Relaxes assumption", "Model specific": "Proposed: sequential ignorability / Markov decision assumption",
"Requires explicit processes": "Agnostic", "Exposure type": "Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 10 PC
put("PC", **{"AI flag": "Standard PC is a generic constraint-based DAG learner under causal sufficiency; this row intentionally excludes the lagged time-series PCMCI setting and assumes orientation from conditional-independence structure.",
"Category": "Causal discovery", "Sub-category": "Constraint-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Inapplicable", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Required", "Faithfulness": "Required",
"IID": "Recommended", "Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 11 PCMCI
put("PCMCI", **{"AI flag": "Designed specifically for time-series causal discovery with lag effects; linked resources emphasize stationarity and no hidden system confounding after conditioning, with explicit lagged-edge detection as a core feature.",
"Category": "Causal discovery", "Sub-category": "Constraint-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Required", "Faithfulness": "Required",
"IID": "Relaxes assumption", "Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Technical but well documented"})
# 12 FCI TsFCI
put("FCI, TsFCI", **{"AI flag": "FCI relaxes causal sufficiency by allowing latent confounders but needs large samples for reliable conditional-independence testing; TsFCI adds time-series structure and stationarity requirements.",
"Category": "Causal discovery", "Sub-category": "Constraint-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Binary, Categorical",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 13 GES TsGFCI
put("GES, TsGFCI", **{"AI flag": "GES is score-based and needs enough data for reliable score comparison; GFCI combines score-based search with latent-confounding logic, and TsGFCI adds time-series/stationarity constraints.",
"Category": "Causal discovery", "Sub-category": "Score-based methods",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 14 DYNOTEARS
put("DYNOTEARS", **{"AI flag": "",
"Category": "Causal discovery, Causal ML", "Sub-category": "Continuous optimization",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Yes",
"Parametric nature": "Parametric, Non-parametric", "Language": "Python",
"Usage": "Technical but well documented"})
# 12 LiNGAM
put("LiNGAM", **{"AI flag": "",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: non-Gaussianity of disturbances", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Possible",
"Parametric nature": "Parametric, Semi-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 13 ANM
put("Additive noise models", **{"AI flag": "",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear, Additivity",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: additive independent noise", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 14 BN learning
put("Bayesian network learning", **{"AI flag": "Broad family covering constraint-, score-, and hybrid DAG learning; linked resources support a generic DAG-learning row, but full edge identifiability still depends on assumptions beyond Markov/Faithfulness alone.",
"Category": "Causal discovery, Alternative paradigms", "Objective": "Causal relationship(s)",
"Estimand": "Oriented link", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Required", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Parametric, Non-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 15 IGCI
put("Info-geom. causal inference", **{"AI flag": "Information-geometric causal inference is primarily bivariate; multivariate use is typically pairwise or screening-based, and the key rationale is independence between the cause distribution and the generating mechanism.",
"Category": "Alternative paradigms", "Objective": "Causal relationship(s)",
"Estimand": "Oriented link", "Type": "Spatial only (cross-sectional)",
"Minimal TS length": "Inapplicable", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Required",
"Model specific": "Proposed: independence of cause distribution and mechanism",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Bivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 16 SES network
put("SES & Network analysis (~adjusted method)", **{"AI flag": "Umbrella label mixing descriptive SES/network analyses with adjusted causal uses; linked resources support network-based understanding, but causal interpretation still depends on confounding control and correct network specification.",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)",
"Objective": "Causal relationship(s), Effect estimation",
"Estimand": "Oriented link, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Relaxes assumption",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Optional",
"Exposure type": "Binary, Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Possible",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 17 diffusion
put("Causal diffusion models", **{"AI flag": "Emerging generative counterfactual approach; linked resource supports scenario-generation use, but identifiability assumptions and biodiversity/RS evidence remain limited in the current literature.",
"Category": "Alternative paradigms", "Objective": "Effect estimation, Scenario projection",
"Estimand": "ATE, CATE, Maps & generalisations",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "Possible",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 18 MSM
put("Marginal structural models", **{"AI flag": "",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)", "Sub-category": "Intermediate confounding",
"Objective": "Effect estimation", "Estimand": "ATE, ATT",
"Type": "Panel data (many samples)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Linear, Non-linear", "No unobserved confounders": "Required",
"No interference": "Required", "Well-defined treatments": "Required",
"Common support (positivity)": "Required", "Causal Markov Condition": "Recommended",
"Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Possible", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 19 G methods
put("G methods", **{"AI flag": "Grouped label covering g-formula, g-estimation, and MSM-style approaches for time-varying confounding; linked resources support this family view under sequential exchangeability and correct model specification.",
"Category": "Alternative paradigms, Adjusted methods (Backdoor C.)", "Sub-category": "Intermediate confounding",
"Objective": "Effect estimation", "Estimand": "ATE, ATT, CATE",
"Type": "Panel data (many samples), Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Required",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 20 ICP
put("Invariant causal prediction", **{"AI flag": "",
"Category": "Alternative paradigms, Causal discovery", "Sub-category": "Prediction-based approaches",
"Objective": "Causal relationship(s), Effect estimation", "Estimand": "Oriented link, CATE",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Proposed: invariance across environments", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Continuous / Time-varying", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 21-24 visualisation helpers
for m in ["Treatment assignment graph", "Covariate timeline", "Reporting measures", "Best practice boxes"]:
    put(m, **{"AI flag": "Ambiguous: visualisation/documentation helper, not an estimator; causal criteria marked Inapplicable where appropriate.",
    "Category": "Versatile tools", "Sub-category": "Visualisation helpers",
    "Objective": "Significance and robustness tests", "Estimand": "Others",
    "Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
    "Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
    "Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
    "RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
    "No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
    "Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
    "Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
    "Model specific": "", "Requires explicit processes": "Agnostic",
    "Exposure type": "Binary, Categorical, Continuous / Time-varying",
    "Number of variables": "Multivariate", "Propaguates uncertainty": "Inapplicable",
    "Handles lag effects": "No", "Parametric nature": "Inapplicable",
    "Language": "R, Python", "Usage": "User-friendly"})
# 25 partial identification
put("Partial identification", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools, Robustness & significance tests",
"Objective": "Significance and robustness tests, Effect estimation", "Estimand": "ATE, ATT, Others",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Relaxes assumption", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Relaxes assumption",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 26 sensitivity
put("Sensitivity analyses", **{"AI flag": "",
"Category": "Versatile tools, Ecology-guided Modelling", "Sub-category": "Robustness & significance tests, Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 27 placebo
put("Placebo tests", **{"AI flag": "Placebo and falsification tests are robustness tools rather than estimators; linked resources support use for checking design credibility, especially where pretreatment fit or null-effect expectations are available.",
"Category": "Versatile tools", "Sub-category": "Robustness & significance tests",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "Good pretreatment fit", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Inapplicable", "Language": "R, Python", "Usage": "Technical but well documented"})
# 28 power
put("Power analyses", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Robustness & significance tests",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Inapplicable",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 29 counterfactual explanations
put("Counterfactual explanations", **{"AI flag": "Ambiguous: interpretability tool for ML predictions; causal validity needs extra assumptions.",
"Category": "Versatile tools", "Sub-category": "Causal interpretability",
"Objective": "Predictive task + interpretability", "Estimand": "Others",
"Type": "Spatial only (cross-sectional)", "Minimal TS length": "Inapplicable",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Yes",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Recommended",
"No interference": "Recommended", "Well-defined treatments": "Recommended",
"Common support (positivity)": "Recommended", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python, R", "Usage": "Technical but well documented"})
# 30 do-calculus
put("Do-calculus rules", **{"AI flag": "",
"Category": "Adjusted methods (Backdoor C.)", "Sub-category": "Alternative effect identification methods",
"Objective": "Effect estimation, Causal relationship(s)", "Estimand": "ATE, Mediation effects, Oriented link",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "All", "Number of variables": "Multivariate",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "Domain-specific skills"})
# 31 linear quadratic trend
put("Linear, quadratic", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Yes", "Fonctional form": "Linear, Quadratic",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "User-friendly"})
# 32 BFast
put("BFast", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Trend, Abrupt change",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Linear, Additivity",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Semi-parametric", "Language": "R, Python",
"Usage": "Technical but well documented, User-friendly"})
# 33 DL change
put("DL change detection", **{"AI flag": "Broad family of supervised and unsupervised deep change detectors; linked review supports RS relevance, but architecture choice, training labels, and weak uncertainty quantification remain major limitations.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Abrupt change, Maps & generalisations",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Needs model-agnostic propagation", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Technical but well documented"})
# 34 diversity metrics
put("Diversity metrics, turnover, variance, phenology, sentinels", **{"AI flag": "Grouped biodiversity indicators rather than a single estimator; linked resources support change detection value, but causal interpretation of detected shifts still requires separate driver attribution methods.",
"Category": "Independent detection", "Sub-category": "Frequently monitored indices",
"Objective": "Detection", "Estimand": "Trend, Abrupt change, Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Compositional",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Inapplicable",
"Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 35 Bayesian structured TS
put("Bayesian Structured TS", **{"AI flag": "BSTS/CausalImpact-style structural time-series approach; linked resources support intervention-style counterfactuals but require a substantial and well-fit pre-intervention period.",
"Category": "Alternative paradigms", "Objective": "Effect estimation, Detection, Scenario projection",
"Estimand": "ATT, Trend, Abrupt change", "Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Additivity, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good pretreatment fit, B/A treatment obs., Stationarity",
"Requires explicit processes": "Agnostic", "Exposure type": "Binary, Continuous / Time-varying",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Inherent capacity",
"Handles lag effects": "Yes", "Parametric nature": "Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 36 TRIM
put("TRIM", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Log-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Others", "Usage": "User-friendly"})
# 37 Markov switching AR
put("Markov switching autoregression models", **{"AI flag": "",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Trend, Abrupt change", "Type": "Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Bivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 38 bootstrapping
put("Bootstrapping", **{"AI flag": "Bootstrap is a general resampling tool for uncertainty quantification rather than a causal estimator; linked resources support broad use, but validity depends on dependence structure and the resampling scheme.",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Inapplicable",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Univariate, Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python", "Usage": "User-friendly, Technical but well documented"})
# 39 Causal GNNs
put("Causal GNNs", **{"AI flag": "Emerging family where validity depends strongly on graph construction and architectural choices; linked resources support moderate-data use in some settings, but uncertainty handling remains architecture-specific rather than generic.",
"Category": "Causal ML", "Objective": "Effect estimation, Causal relationship(s)",
"Estimand": "CATE, ATE, Oriented link", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "No", "Fonctional form": "Non-linear, Assumption-free",
"No unobserved confounders": "Required", "No interference": "Relaxes assumption",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Relaxes assumption",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Possible",
"Parametric nature": "Non-parametric", "Language": "Python", "Usage": "Domain-specific skills"})
# 40 conformal
put("Conformal inference", **{"AI flag": "",
"Category": "Versatile tools", "Sub-category": "Uncertainty tools",
"Objective": "Significance and robustness tests", "Estimand": "Others",
"Type": "Spatial only (cross-sectional), Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "Python, R", "Usage": "Technical but well documented"})
# 41 first-difference
put("First-difference estimator", **{"AI flag": "",
"Category": "Quasi-experiments", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Parallel trends, B/A treatment obs.", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 42 long difference
put("Long difference estimator", **{"AI flag": "",
"Category": "Quasi-experiments", "Objective": "Effect estimation",
"Estimand": "ATT, ATE", "Type": "Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Linear",
"No unobserved confounders": "Relaxes assumption", "No interference": "Required",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Parallel trends, B/A treatment obs.", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric", "Language": "R, Python", "Usage": "Technical but well documented"})
# 43 variance partitioning
put("Variance partitioning / Variable importance", **{"AI flag": "Descriptive variance attribution rather than intervention causality; linked resources support explanatory usefulness, but inferred importance remains model- and correlation-dependent unless stronger causal assumptions hold.",
"Category": "Ecology-guided Modelling", "Objective": "Predictive task + interpretability, Detection",
"Estimand": "Others, Maps & generalisations", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Partially",
"RS-data proven": "Yes", "Fonctional form": "Linear, Non-linear, Assumption-free",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate, High-dimensional (p≫n)",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric, Semi-parametric", "Language": "R, Python",
"Usage": "User-friendly, Technical but well documented"})
# 44 moderator
put("Moderator analysis", **{"AI flag": "",
"Category": "Adjusted methods (Backdoor C.)", "Objective": "Effect estimation",
"Estimand": "CATE, ATE", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Required", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Good covariate balance", "Requires explicit processes": "Agnostic",
"Exposure type": "Binary, Categorical, Continuous / Time-varying",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Parametric, Semi-parametric",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 45 process-based models
put("Process-based models", **{"AI flag": "",
"Category": "Counterfactual & future simulations", "Objective": "Scenario projection, Effect estimation",
"Estimand": "Maps & generalisations, Trend, Others",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "Dispersal, reproduction, mortality", "Requires explicit processes": "Yes",
"Exposure type": "Continuous / Time-varying, Categorical, Multivariate",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "Yes", "Parametric nature": "Parametric, Semi-parametric",
"Language": "R, Python, Others", "Usage": "Domain-specific skills"})
# 46 CLUE
put("CLUE model", **{"AI flag": "Ambiguous: land-use allocation scenario model; causal interpretation needs scenario assumptions.",
"Category": "Counterfactual & future simulations", "Objective": "Scenario projection",
"Estimand": "Maps & generalisations", "Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear, Non-linear, Rule-based",
"No unobserved confounders": "Recommended", "No interference": "Relaxes assumption",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Yes",
"Exposure type": "Categorical, Continuous / Time-varying, Multivariate",
"Number of variables": "Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Parametric, Rule-based",
"Language": "Others, GIS", "Usage": "Domain-specific skills, Technical but well documented"})
# 47 ARDL
put("ARDL", **{"AI flag": "ARDL is a distributed-lag regression framework for dynamic associations and cointegration-style settings; linked resources support lag handling and parametric time-series use under stationarity/bounds-test assumptions.",
"Category": "Ecology-guided Modelling, Adjusted methods (Backdoor C.)", "Sub-category": "Linear regressions & extensions",
"Objective": "Effect estimation, Detection", "Estimand": "ATE, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Recommended", "Common support (positivity)": "Recommended",
"Causal Markov Condition": "Recommended", "Faithfulness": "Recommended", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Parametric", "Language": "R, Python, Others",
"Usage": "Technical but well documented"})
# 48 Bayesian change point
put("Bayesian Change point detection", **{"AI flag": "Bayesian change-point detection explicitly represents uncertainty over breakpoint location and number; linked resources support abrupt-change detection with built-in probabilistic inference.",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Abrupt change, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Bivariate",
"Propaguates uncertainty": "Inherent capacity", "Handles lag effects": "No",
"Parametric nature": "Semi-parametric, Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 49 Functional causal model
put("Functional causal model", **{"AI flag": "Umbrella label for ANM/LiNGAM/related functional causal models; identifiability depends on specific functional restrictions and independent-noise assumptions, which are harder to verify in high-dimensional settings.",
"Category": "Causal discovery", "Sub-category": "Asymmetry-based",
"Objective": "Causal relationship(s)", "Estimand": "Oriented link",
"Type": "Spatial only (cross-sectional), Panel data (many samples)",
"Minimal TS length": "Handles ≤ 10, ≥ 10", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "No", "Fonctional form": "Non-linear, Additivity",
"No unobserved confounders": "Required", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Required", "Faithfulness": "Recommended", "IID": "Required",
"Model specific": "Proposed: restricted functional form with independent noise",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Bivariate, Multivariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Semi-parametric, Non-parametric",
"Language": "Python, R", "Usage": "Technical but well documented"})
# 50 CCDC
put("Continuous Change Detection and Classification (CCDC)", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Trend, Abrupt change",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Yes",
"RS-data proven": "Yes", "Fonctional form": "Linear, Additivity",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Parametric, Semi-parametric", "Language": "Python, Others, GIS",
"Usage": "Technical but well documented, User-friendly"})
# 51 Mann-Kendall
put("Mann-Kendall test (+ seq. extension)", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection, Significance and robustness tests", "Estimand": "Trend",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "Partially", "RS-data proven": "Yes",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 52 Pettitt
put("Pettitt's Test", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection, Significance and robustness tests", "Estimand": "Abrupt change",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "No: requires prelim. correction", "RS-data proven": "Few applications",
"Fonctional form": "Assumption-free", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 53 Sen slope
put("Sen's slope", **{"AI flag": "",
"Category": "Independent detection", "Sub-category": "Trend detection",
"Objective": "Detection", "Estimand": "Trend",
"Type": "Time-series (one sample)", "Minimal TS length": "≥ 10, ≥ 100",
"Handles few samples": "10 to 100", "Handles huge datasets (n)": "Most do",
"Handles missing data": "Partially", "RS-data proven": "Yes",
"Fonctional form": "Linear", "No unobserved confounders": "Inapplicable",
"No interference": "Inapplicable", "Well-defined treatments": "Inapplicable",
"Common support (positivity)": "Inapplicable", "Causal Markov Condition": "Inapplicable",
"Faithfulness": "Inapplicable", "IID": "Recommended", "Model specific": "",
"Requires explicit processes": "Agnostic", "Exposure type": "Continuous / Time-varying",
"Number of variables": "Univariate", "Propaguates uncertainty": "Model-specific tools",
"Handles lag effects": "No", "Parametric nature": "Non-parametric",
"Language": "R, Python", "Usage": "User-friendly"})
# 54 Post-Classification Comparison (PCC)
put("Post-Classification Comparison (PCC)", **{"AI flag": "Operational RS change detector comparing classified pre/post maps; linked resources support change mapping, but accuracy depends heavily on the upstream classifier, sensor, and threshold choices.",
"Category": "Independent detection", "Sub-category": "RS breakpoint detection",
"Objective": "Detection", "Estimand": "Abrupt change, Maps & generalisations",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10", "Handles few samples": "Yes ≤ 10",
"Handles huge datasets (n)": "Yes", "Handles missing data": "Yes",
"RS-data proven": "Yes", "Fonctional form": "Rule-based, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Rule-based",
"Language": "Python, Others, GIS", "Usage": "User-friendly, Technical but well documented"})
# 55 Information transfer
put("Information transfer", **{"AI flag": "Information-theoretic approach (transfer entropy / information flow) targeting predictive precedence rather than intervention causality; linked resources support mostly bivariate or pairwise time-series use.",
"Category": "Causal discovery, Alternative paradigms", "Sub-category": "Prediction-based approaches",
"Objective": "Causal relationship(s), Predictive task + interpretability", "Estimand": "Oriented link",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "No",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})
# 56 CAT transformation
put("CAT transformation (Hird et al. 2016)", **{"AI flag": "Single-study change-after-transformation detector based on transformed dense time series; linked resource supports original use case, but broader generalization beyond that context remains limited.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Abrupt change, Trend", "Type": "Time-series (one sample)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "Stationarity", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Univariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "No",
"Parametric nature": "Non-parametric", "Language": "R, Python",
"Usage": "Technical but well documented"})
# 57 Trajectory classification
put("Trajectory classification (Pélissié et al. 2024)", **{"AI flag": "Single-study ecological trajectory classifier; linked resource supports abrupt-shift screening, but transferability outside the original ecological context remains uncertain.",
"Category": "Independent detection", "Objective": "Detection",
"Estimand": "Trend, Maps & generalisations", "Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "Partially",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Inapplicable", "No interference": "Inapplicable",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Recommended",
"Model specific": "", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying, Categorical",
"Number of variables": "Univariate, Multivariate", "Propaguates uncertainty": "Needs model-agnostic propagation",
"Handles lag effects": "No", "Parametric nature": "Non-parametric, Rule-based",
"Language": "R, Python", "Usage": "Technical but well documented"})
# 58 Dynamical footprint
put("Dynamical footprint analysis (Cano et al. 2025)", **{"AI flag": "Single-study dynamical-footprint approach for abrupt-shift susceptibility; linked resource supports dynamical-systems framing, but broader cross-system generalization remains uncertain.",
"Category": "Independent detection", "Objective": "Detection, Causal relationship(s)",
"Estimand": "Oriented link, Abrupt change, Trend",
"Type": "Time-series (one sample), Panel data (many samples)",
"Minimal TS length": "≥ 10, ≥ 100", "Handles few samples": "10 to 100",
"Handles huge datasets (n)": "Most do", "Handles missing data": "No: requires prelim. correction",
"RS-data proven": "Few applications", "Fonctional form": "Assumption-free, Non-linear",
"No unobserved confounders": "Recommended", "No interference": "Recommended",
"Well-defined treatments": "Inapplicable", "Common support (positivity)": "Inapplicable",
"Causal Markov Condition": "Inapplicable", "Faithfulness": "Inapplicable", "IID": "Relaxes assumption",
"Model specific": "Dynamical system", "Requires explicit processes": "Agnostic",
"Exposure type": "Continuous / Time-varying", "Number of variables": "Bivariate, Multivariate",
"Propaguates uncertainty": "Model-specific tools", "Handles lag effects": "Yes",
"Parametric nature": "Non-parametric", "Language": "Python, R",
"Usage": "Technical but well documented"})

def main():
    with open(IN, encoding="utf-8", newline="") as f:
        content = f.read()
    lines = content.split("\n")
    # header line index 3 (has duplicate 'Status': idx1=doc Status, idx5=assessment Status)
    hdr = [h.strip() for h in lines[3].split("\t")]
    assert hdr == HDR, f"header mismatch: {hdr[:6]}"
    updated = 0
    for i in range(4, len(lines)):
        if not lines[i].strip():
            continue
        parts = lines[i].split("\t")
        while len(parts) < len(HDR):
            parts.append("")
        method = parts[4].strip()
        status = parts[5].strip()
        if status != "Complete" and method in A:
            patch = A[method]
            for k, v in patch.items():
                # 'Status' key means assessment Status at index 5 (not doc Status at index 1)
                if k == "Status":
                    j = 5
                else:
                    j = HDR.index(k)
                parts[j] = v
            # Mark manual-resource methods as corrected AI completions, keep the
            # original AI label for the remaining bulk-assessed rows.
            parts[3] = CORRECTED_AI_TAG if method in CORRECTED_METHODS else AI_TAG
            # ensure length
            lines[i] = "\t".join(parts[:len(HDR)])
            updated += 1
    with open(IN, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))
    print(f"updated {updated} rows")

if __name__ == "__main__":
    main()
